;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s -all --flatten -S -o - | filecheck %s

;; Flattening of try_table. A catch clause has no body - it names a destination
;; label, and the caught values are delivered there implicitly, on the stack.
;; Flatten interposes a fresh block that receives those values and spills them
;; into the destination's break temp, so that the destination itself becomes a
;; none-typed block followed by a get of that local.

(module
 ;; CHECK:      (tag $e-i32 (type $2) (param i32))
 (tag $e-i32 (param i32))
 ;; CHECK:      (tag $e-i64 (type $3) (param i64))
 (tag $e-i64 (param i64))
 ;; CHECK:      (tag $e-none (type $0))
 (tag $e-none)

 ;; A try_table with no value-carrying catch needs no interposed block.
 ;; CHECK:      (func $catch-all-no-values (type $0)
 ;; CHECK-NEXT:  (block $l
 ;; CHECK-NEXT:   (try_table (catch_all $l)
 ;; CHECK-NEXT:    (nop)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $catch-all-no-values
  (block $l
   (try_table (catch_all $l)
    (nop)
   )
  )
 )

 ;; The shape that libc's sigsetjmp has: a catch that delivers an i32 to a
 ;; valued block, whose value is then used.
 ;; CHECK:      (func $catch-value (type $1) (result i32)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (block $l
 ;; CHECK-NEXT:   (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:    (local.set $0
 ;; CHECK-NEXT:     (block $flatten-try-table-catch$1 (result i32)
 ;; CHECK-NEXT:      (try_table (catch $e-i32 $flatten-try-table-catch$1)
 ;; CHECK-NEXT:       (throw $e-i32
 ;; CHECK-NEXT:        (i32.const 42)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (unreachable)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br $l)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $1
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $catch-value (result i32)
  (block $l (result i32)
   (try_table (catch $e-i32 $l)
    (throw $e-i32
     (i32.const 42)
    )
   )
   (unreachable)
  )
 )

 ;; The body can complete normally, so the branch out of the interposed block
 ;; is live.
 ;; CHECK:      (func $catch-value-reachable-body (type $1) (result i32)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (block $l
 ;; CHECK-NEXT:   (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:    (local.set $0
 ;; CHECK-NEXT:     (block $flatten-try-table-catch$1 (result i32)
 ;; CHECK-NEXT:      (try_table (catch $e-i32 $flatten-try-table-catch$1)
 ;; CHECK-NEXT:       (nop)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br $l)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $0
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $1
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $catch-value-reachable-body (result i32)
  (block $l (result i32)
   (try_table (catch $e-i32 $l)
    (nop)
   )
   (i32.const 1)
  )
 )

 ;; Two catches delivering different values to two different destinations.
 ;; CHECK:      (func $two-catches (type $4) (result i64)
 ;; CHECK-NEXT:  (local $0 i64)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (local $3 i64)
 ;; CHECK-NEXT:  (local $4 i64)
 ;; CHECK-NEXT:  (block $outer
 ;; CHECK-NEXT:   (block $l32
 ;; CHECK-NEXT:    (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:     (local.set $1
 ;; CHECK-NEXT:      (block $flatten-try-table-catch$2 (result i32)
 ;; CHECK-NEXT:       (local.set $0
 ;; CHECK-NEXT:        (block $flatten-try-table-catch$1 (result i64)
 ;; CHECK-NEXT:         (try_table (catch $e-i32 $flatten-try-table-catch$2) (catch $e-i64 $flatten-try-table-catch$1)
 ;; CHECK-NEXT:          (nop)
 ;; CHECK-NEXT:         )
 ;; CHECK-NEXT:         (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (br $outer)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br $l32)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (local.set $0
 ;; CHECK-NEXT:     (i64.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br $outer)
 ;; CHECK-NEXT:    (unreachable)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $2
 ;; CHECK-NEXT:    (local.get $1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $3
 ;; CHECK-NEXT:    (i64.extend_i32_u
 ;; CHECK-NEXT:     (local.get $2)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $0
 ;; CHECK-NEXT:    (local.get $3)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $4
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return
 ;; CHECK-NEXT:   (local.get $4)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $two-catches (result i64)
  (block $outer (result i64)
   (block $l32 (result i32)
    (try_table (catch $e-i32 $l32) (catch $e-i64 $outer)
     (nop)
    )
    (br $outer
     (i64.const 0)
    )
   )
   (i64.extend_i32_u)
  )
 )

 ;; A value-carrying catch alongside a valueless one.
 ;; CHECK:      (func $mixed (type $0)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (block $none
 ;; CHECK-NEXT:   (block $l
 ;; CHECK-NEXT:    (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:     (local.set $0
 ;; CHECK-NEXT:      (block $flatten-try-table-catch$1 (result i32)
 ;; CHECK-NEXT:       (try_table (catch $e-none $none) (catch $e-i32 $flatten-try-table-catch$1)
 ;; CHECK-NEXT:        (nop)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br $l)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br $none)
 ;; CHECK-NEXT:    (unreachable)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $1
 ;; CHECK-NEXT:    (local.get $0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (local.get $1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $mixed
  (block $none
   (block $l (result i32)
    (try_table (catch $e-none $none) (catch $e-i32 $l)
     (nop)
    )
    (br $none)
   )
   (drop)
  )
 )

 ;; The try_table itself flows a value out of its body.
 ;; CHECK:      (func $try-table-value (type $1) (result i32)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (local $3 i32)
 ;; CHECK-NEXT:  (block $l
 ;; CHECK-NEXT:   (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:    (local.set $1
 ;; CHECK-NEXT:     (block $flatten-try-table-catch$1 (result i32)
 ;; CHECK-NEXT:      (try_table (catch $e-i32 $flatten-try-table-catch$1)
 ;; CHECK-NEXT:       (local.set $0
 ;; CHECK-NEXT:        (i32.const 7)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br $l)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $2
 ;; CHECK-NEXT:    (local.get $0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $1
 ;; CHECK-NEXT:    (local.get $2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $3
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return
 ;; CHECK-NEXT:   (local.get $3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $try-table-value (result i32)
  (block $l (result i32)
   (try_table (result i32) (catch $e-i32 $l)
    (i32.const 7)
   )
  )
 )

 ;; catch_ref delivers the tag payload plus an exnref.
 ;; CHECK:      (func $catch-ref (type $1) (result i32)
 ;; CHECK-NEXT:  (local $scratch (tuple i32 exnref))
 ;; CHECK-NEXT:  (local $scratch_1 i32)
 ;; CHECK-NEXT:  (local $2 (tuple i32 exnref))
 ;; CHECK-NEXT:  (local $3 (tuple i32 exnref))
 ;; CHECK-NEXT:  (local $4 (tuple i32 exnref))
 ;; CHECK-NEXT:  (local $5 i32)
 ;; CHECK-NEXT:  (local $6 (tuple i32 exnref))
 ;; CHECK-NEXT:  (local $7 exnref)
 ;; CHECK-NEXT:  (local $8 i32)
 ;; CHECK-NEXT:  (local $9 i32)
 ;; CHECK-NEXT:  (local $10 i32)
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (block $l
 ;; CHECK-NEXT:    (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:     (local.set $2
 ;; CHECK-NEXT:      (block $flatten-try-table-catch$1 (type $5) (result i32 (ref exn))
 ;; CHECK-NEXT:       (try_table (catch_ref $e-i32 $flatten-try-table-catch$1)
 ;; CHECK-NEXT:        (unreachable)
 ;; CHECK-NEXT:        (unreachable)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br $l)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $3
 ;; CHECK-NEXT:    (local.get $2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $scratch
 ;; CHECK-NEXT:    (local.get $3)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $4
 ;; CHECK-NEXT:    (local.get $scratch)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $5
 ;; CHECK-NEXT:    (tuple.extract 2 0
 ;; CHECK-NEXT:     (local.get $4)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $scratch_1
 ;; CHECK-NEXT:    (local.get $5)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $6
 ;; CHECK-NEXT:    (local.get $scratch)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $7
 ;; CHECK-NEXT:    (tuple.extract 2 1
 ;; CHECK-NEXT:     (local.get $6)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (local.get $7)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $8
 ;; CHECK-NEXT:    (local.get $scratch_1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $9
 ;; CHECK-NEXT:    (local.get $8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $10
 ;; CHECK-NEXT:   (local.get $9)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return
 ;; CHECK-NEXT:   (local.get $10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $catch-ref (result i32)
  (block $l (result i32 exnref)
   (try_table (catch_ref $e-i32 $l)
    (unreachable)
   )
  )
  (drop)
 )

 ;; catch_all_ref delivers only an exnref.
 ;; CHECK:      (func $catch-all-ref (type $0)
 ;; CHECK-NEXT:  (local $0 exnref)
 ;; CHECK-NEXT:  (local $1 exnref)
 ;; CHECK-NEXT:  (block $l
 ;; CHECK-NEXT:   (block $flatten-try-table-escape$0
 ;; CHECK-NEXT:    (local.set $0
 ;; CHECK-NEXT:     (block $flatten-try-table-catch$1 (result (ref exn))
 ;; CHECK-NEXT:      (try_table (catch_all_ref $flatten-try-table-catch$1)
 ;; CHECK-NEXT:       (nop)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br $flatten-try-table-escape$0)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br $l)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $1
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $catch-all-ref
  (drop
   (block $l (result exnref)
    (try_table (catch_all_ref $l)
     (nop)
    )
    (unreachable)
   )
  )
 )
)
