;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; An atomic.fence has no value and touches no location, so the constant
;; expression runner can "evaluate" it without observing anything -- but it
;; orders the surrounding accesses with respect to other threads, and removing
;; it is a miscompile for any threaded module (e.g. C11
;; atomic_thread_fence(memory_order_seq_cst) and musl's a_barrier() are
;; lowered by LLVM to exactly this instruction). Precompute must keep it,
;; including when it sits inside an otherwise-constant expression, and so must
;; the default optimization pipeline that runs Precompute. The $fold-* functions
;; are the positive control: constant arithmetic must still fold, both alone
;; and next to a fence, so the fence survives because it is a fence and not
;; because folding stopped working.

;; RUN: wasm-opt %s --enable-threads --precompute -S -o - | filecheck %s
;; RUN: wasm-opt %s --enable-threads --precompute-propagate -S -o - | filecheck %s --check-prefix=PROP
;; RUN: wasm-opt %s --enable-threads -O2 -S -o - | filecheck %s --check-prefix=O2

(module
  ;; CHECK:      (memory $mem 1 1 shared)
  ;; PROP:      (memory $mem 1 1 shared)
  ;; O2:      (memory $mem 1 1 shared)
  (memory $mem 1 1 shared)

  ;; CHECK:      (export "lone-fence" (func $lone-fence))
  ;; PROP:      (export "lone-fence" (func $lone-fence))
  ;; O2:      (export "lone-fence" (func $lone-fence))
  (export "lone-fence" (func $lone-fence))
  ;; CHECK:      (export "fence-then-const" (func $fence-then-const))
  ;; PROP:      (export "fence-then-const" (func $fence-then-const))
  ;; O2:      (export "fence-then-const" (func $fence-then-const))
  (export "fence-then-const" (func $fence-then-const))
  ;; CHECK:      (export "store-fence-store" (func $store-fence-store))
  ;; PROP:      (export "store-fence-store" (func $store-fence-store))
  ;; O2:      (export "store-fence-store" (func $store-fence-store))
  (export "store-fence-store" (func $store-fence-store))
  ;; CHECK:      (export "fold-alone" (func $fold-alone))
  ;; PROP:      (export "fold-alone" (func $fold-alone))
  ;; O2:      (export "fold-alone" (func $fold-alone))
  (export "fold-alone" (func $fold-alone))
  ;; CHECK:      (export "fold-beside-fence" (func $fold-beside-fence))
  ;; PROP:      (export "fold-beside-fence" (func $fold-beside-fence))
  ;; O2:      (export "fold-beside-fence" (func $fold-beside-fence))
  (export "fold-beside-fence" (func $fold-beside-fence))


  ;; CHECK:      (func $lone-fence
  ;; CHECK-NEXT:  (atomic.fence)
  ;; CHECK-NEXT: )
  ;; PROP:      (func $lone-fence
  ;; PROP-NEXT:  (atomic.fence)
  ;; PROP-NEXT: )
  ;; O2:      (func $lone-fence
  ;; O2-NEXT:  (atomic.fence)
  ;; O2-NEXT: )
  (func $lone-fence
    (atomic.fence)
  )

  ;; CHECK:      (func $fence-then-const (result i32)
  ;; CHECK-NEXT:  (atomic.fence)
  ;; CHECK-NEXT:  (i32.const 42)
  ;; CHECK-NEXT: )
  ;; PROP:      (func $fence-then-const (result i32)
  ;; PROP-NEXT:  (atomic.fence)
  ;; PROP-NEXT:  (i32.const 42)
  ;; PROP-NEXT: )
  ;; O2:      (func $fence-then-const (result i32)
  ;; O2-NEXT:  (atomic.fence)
  ;; O2-NEXT:  (i32.const 42)
  ;; O2-NEXT: )
  (func $fence-then-const (result i32)
    (block (result i32)
      (atomic.fence)
      (i32.const 42)
    )
  )

  ;; CHECK:      (func $store-fence-store
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (atomic.fence)
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (i32.const 4)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; PROP:      (func $store-fence-store
  ;; PROP-NEXT:  (i32.store
  ;; PROP-NEXT:   (i32.const 0)
  ;; PROP-NEXT:   (i32.const 1)
  ;; PROP-NEXT:  )
  ;; PROP-NEXT:  (atomic.fence)
  ;; PROP-NEXT:  (i32.store
  ;; PROP-NEXT:   (i32.const 4)
  ;; PROP-NEXT:   (i32.const 1)
  ;; PROP-NEXT:  )
  ;; PROP-NEXT: )
  ;; O2:      (func $store-fence-store
  ;; O2-NEXT:  (i32.store
  ;; O2-NEXT:   (i32.const 0)
  ;; O2-NEXT:   (i32.const 1)
  ;; O2-NEXT:  )
  ;; O2-NEXT:  (atomic.fence)
  ;; O2-NEXT:  (i32.store
  ;; O2-NEXT:   (i32.const 4)
  ;; O2-NEXT:   (i32.const 1)
  ;; O2-NEXT:  )
  ;; O2-NEXT: )
  (func $store-fence-store
    (i32.store
      (i32.const 0)
      (i32.const 1)
    )
    (atomic.fence)
    (i32.store
      (i32.const 4)
      (i32.const 1)
    )
  )

  ;; CHECK:      (func $fold-alone (result i32)
  ;; CHECK-NEXT:  (i32.const 43)
  ;; CHECK-NEXT: )
  ;; PROP:      (func $fold-alone (result i32)
  ;; PROP-NEXT:  (i32.const 43)
  ;; PROP-NEXT: )
  ;; O2:      (func $fold-alone (result i32)
  ;; O2-NEXT:  (i32.const 43)
  ;; O2-NEXT: )
  (func $fold-alone (result i32)
    (i32.add
      (i32.const 40)
      (i32.const 3)
    )
  )

  ;; CHECK:      (func $fold-beside-fence (result i32)
  ;; CHECK-NEXT:  (atomic.fence)
  ;; CHECK-NEXT:  (i32.const 48)
  ;; CHECK-NEXT: )
  ;; PROP:      (func $fold-beside-fence (result i32)
  ;; PROP-NEXT:  (atomic.fence)
  ;; PROP-NEXT:  (i32.const 48)
  ;; PROP-NEXT: )
  ;; O2:      (func $fold-beside-fence (result i32)
  ;; O2-NEXT:  (atomic.fence)
  ;; O2-NEXT:  (i32.const 48)
  ;; O2-NEXT: )
  (func $fold-beside-fence (result i32)
    (block (result i32)
      (atomic.fence)
      (i32.mul
        (i32.const 6)
        (i32.const 8)
      )
    )
  )
)
